name: walt
description: food delivery sample App

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  flutter_riverpod: ^1.0.3
  flutter_hooks: ^0.18.3
  hooks_riverpod: ^1.0.3

  webview_flutter: ^3.0.2
  palette_generator: ^0.3.3
  cloud_firestore: ^3.1.12
  built_collection: ^5.1.1
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  logger: ^1.1.0
  youtube_player_flutter: ^8.0.0
  flutter_dotenv: ^5.0.2
  freezed_annotation: ^2.0.1
  json_annotation: ^4.4.0
  smooth_page_indicator: ^1.0.0+2
  preload_page_view: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.10
  json_serializable: ^6.1.6
  freezed: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - .env
